[package]
name = "bytode"
version.workspace = true
edition.workspace = true

[dependencies]
bytode-agent = { path = "../bytode-agent" }
bytode-common = { path = "../bytode-common" }
bytode-llm = { path = "../bytode-llm" }
bytode-lsp = { path = "../bytode-lsp" }
bytode-tools = { path = "../bytode-tools" }
clap.workspace = true
crossterm.workspace = true
dirs.workspace = true
futures.workspace = true
git2.workspace = true
ratatui.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
